- name: Watch for file change
  hosts: localhost
  sources:
    - name: file watcher
      ansible.eda.file_watch:
        path: /tmp/watchme.txt

  rules:
    - name: run playbook when file changes
      condition: event.type == "modified"
      action:
        run_playbook:
          name: playbooks/playbook_on_file_change.yml

